apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-cron
  labels:
    app: kuber-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-cron
  template:
    metadata:
      labels:
        app: kuber-cron
    spec:
      containers:
      - name: kuber-cron
        image: kuber-cron:latest  # Using our local image
        imagePullPolicy: Never    # Never pull from registry
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /var/log/kuber-cron
        env:
        - name: KUBER_CRON_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: kuber-cron-config
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber-cron-config
data:
  crontab: |
    # Run CPU stress test every minute
    * * * * * python src/jobs/cpu_stress.py >> /var/log/kuber-cron/cpu_stress.log 2>&1

    # Run backup job every hour
    0 * * * * python src/jobs/backup.py >> /var/log/kuber-cron/backup.log 2>&1 