apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-cron
  labels:
    app: kuber-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-cron
  template:
    metadata:
      labels:
        app: kuber-cron
    spec:
      containers:
      - name: kuber-cron
        image: kuber-cron:latest  # Using our local image
        imagePullPolicy: Never    # Never pull from registry
        workingDir: /app
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - name: logs-volume
          mountPath: /var/log/kuber-cron
        env:
        - name: KUBER_CRON_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 2
      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: kuber-cron-logs-pvc 